import { dark } from "@clerk/themes";

export const clerkAppearance = {
  baseTheme: dark,
  variables: {
    colorPrimary: "#6366f1",
    colorWarning: "#ef4444",
    colorTextOnPrimaryBackground: "#ffffff",
    colorBackground: "#0a0a0b",
    colorInputBackground: "rgba(255, 255, 255, 0.08)",
    colorInputText: "#ffffff",
    colorText: "#ffffff",
    colorTextSecondary: "#a1a1aa",
    colorNeutral: "#ffffff",
    colorForeground: "#ffffff",
    colorMutedForeground: "#a1a1aa",
    colorMuted: "rgba(255, 255, 255, 0.06)",
    colorShimmer: "rgba(255, 255, 255, 0.08)",
    colorRing: "rgba(99, 102, 241, 0.5)",
    colorModalBackdrop: "rgba(0, 0, 0, 0.7)",
    colorInput: "rgba(255, 255, 255, 0.08)",
    colorInputForeground: "#ffffff",
    colorDanger: "#ef4444",
    colorSuccess: "#22c55e",
    borderRadius: "1rem",
    fontFamily: "var(--font-sans)",
    fontSize: "0.875rem",
  },
  elements: {
    rootBox: "w-full",
    card: "rounded-[2rem] border border-white/10 shadow-2xl shadow-black/60 p-0 w-full max-w-full bg-[#0a0a0b]",
    navbar: "rounded-l-[2rem] border-r border-white/5 bg-[#0a0a0b] py-8 px-4",
    navbarButton: "rounded-xl transition-colors hover:bg-white/5",
    navbarButtonActive: "bg-white/10 text-white",
    scrollBox: "rounded-none bg-[#0a0a0b] px-6 py-8",
    pageScrollBox: "rounded-r-[2rem] bg-[#0a0a0b]",
    page: "bg-[#0a0a0b] text-white w-full",
    profileSection: "border-b border-white/5 pb-6 mb-6 w-full",
    profileSectionPrimaryButton: "rounded-full bg-white/5 hover:bg-white/10 text-white text-xs font-medium px-3 py-1.5 transition-colors border border-white/10",
    profileSectionContent: "text-white w-full",
    profileSectionTitleText: "font-heading text-lg font-semibold border-b border-white/5 pb-4 w-full text-white mb-4",
    profileSectionTitle: "w-full",
    profileSectionItem: "py-3",
    profileSectionItemLabel: "text-muted-foreground text-xs font-medium",
    profileSectionItemValue: "text-white text-sm font-medium",
    profileSectionItem__emailAddresses: "py-3",
    profileSectionItem__connectedAccounts: "py-3",
    userButtonPopoverCard: "rounded-3xl border border-white/10 shadow-2xl shadow-black/40 bg-[#0a0a0b]",
    userButtonPopoverActionButton: "rounded-xl hover:bg-white/5 transition-colors mx-2 my-1",
    userButtonPopoverActionButtonText: "font-medium text-sm text-white",
    userButtonPopoverActionButtonIcon: "text-muted-foreground",
    userButtonPopoverFooter: "hidden",
    userPreviewMainIdentifier: "text-base font-semibold text-white",
    userPreviewSecondaryIdentifier: "text-xs text-muted-foreground",
    formButtonPrimary: "rounded-full bg-primary text-white hover:bg-primary/90 hover:scale-[1.02] transition-all font-medium text-sm h-11 border-none shadow-lg shadow-primary/20",
    formButtonReset: "rounded-full hover:bg-white/5 text-white text-sm font-medium h-11",
    formFieldInput: "glass-card border-white/10 h-11 rounded-xl focus:ring-1 focus:ring-primary focus:border-primary text-white text-sm px-3.5 transition-all bg-white/5",
    formFieldLabel: "text-xs font-medium text-muted-foreground mb-1.5",
    formFieldLabelRow: "mb-1.5",
    formFieldAction: "text-primary hover:text-primary/90 text-xs font-medium",
    formFieldInputGroup: "rounded-xl",
    formHeaderTitle: "font-heading text-2xl font-semibold tracking-tight text-white mb-1",
    formHeaderSubtitle: "text-sm text-muted-foreground",
    headerTitle: "font-heading text-3xl font-semibold tracking-tight text-white mb-1",
    headerSubtitle: "text-sm text-muted-foreground",
    socialButtonsBlockButton: "glass-card border-white/10 hover:border-white/20 hover:bg-white/10 transition-all text-white h-11 rounded-xl bg-white/5",
    socialButtonsBlockButtonText: "font-medium text-sm text-white",
    dividerLine: "bg-white/10",
    dividerText: "text-muted-foreground text-xs font-medium",
    footerActionText: "text-muted-foreground text-sm",
    footerActionLink: "text-primary hover:text-primary/90 transition-colors font-medium",
    identityPreviewTextPrimary: "text-sm font-medium text-white",
    identityPreviewEditButtonIcon: "text-primary hover:text-primary/90 transition-colors",
    identityPreview: "rounded-xl bg-white/5 border border-white/10 px-3 py-2.5",
    breadcrumbsItem: "text-sm font-medium text-white",
    breadcrumbsItemCurrent: "text-white font-semibold",
    breadcrumbsSeparator: "text-white/20",
    avatarBox: "rounded-full border border-white/10 hover:border-white/20 transition-colors overflow-hidden w-9 h-9",
    avatarImage: "rounded-full object-cover",
    userButtonTrigger: "rounded-full focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-black",
    organizationSwitcherTrigger: "glass-card border-white/10 rounded-xl px-3 py-2 text-sm font-medium hover:bg-white/5 transition-colors text-white",
    badge: "rounded-full bg-white/10 text-white text-xs px-2 py-0.5 font-medium",
    badgePrimary: "rounded-full bg-primary/20 text-primary text-xs px-2 py-0.5 font-medium",
    button: "rounded-full",
    backRow: "text-white hover:bg-white/5 rounded-xl px-2 py-1",
    menuList: "bg-transparent",
    menuItem: "rounded-xl hover:bg-white/5 text-white px-3 py-2",
    menuButton: "rounded-xl hover:bg-white/5 text-white",
    modal: "rounded-3xl border border-white/10 shadow-2xl shadow-black/40 bg-[#0a0a0b]",
    modalContent: "bg-[#0a0a0b]",
    modalCloseButton: "text-muted-foreground hover:text-white hover:bg-white/5 rounded-full",
    otpCodeFieldInput: "bg-white/5 border-white/10 text-white rounded-xl",
    alert: "rounded-xl border border-white/10 bg-white/5",
    alertText: "text-sm text-white",
    table: "w-full",
    tableHead: "text-muted-foreground text-xs font-medium",
    tableRow: "border-b border-white/5 hover:bg-white/5",
    tableCell: "text-white text-sm py-3",
    internal: "text-primary",
    selectButton: "rounded-xl bg-white/5 border border-white/10 text-white h-11 hover:bg-white/10",
    selectSearchInput: "rounded-xl bg-white/5 border border-white/10 text-white",
    selectOption: "rounded-lg text-white hover:bg-white/5",
    selectList: "bg-[#0a0a0b] border border-white/10",
    tagInputContainer: "rounded-xl bg-white/5 border border-white/10",
    tagPill: "rounded-full bg-primary/20 text-primary text-xs",
    phoneInputBox: "rounded-xl bg-white/5 border border-white/10",
    fileDropZone: "rounded-xl border-dashed border-white/10 bg-white/5 hover:bg-white/10",
    verificationLinkStatusBox: "rounded-xl bg-white/5 border border-white/10",
  },
  layout: {
    socialButtonsPlacement: "bottom" as const,
    shimmer: true,
  },
};
