import { dark } from "@clerk/themes";

export const clerkAppearance = {
  baseTheme: dark,
  variables: {
    colorPrimary: "#ccff00",
    colorWarning: "#ccff00",
    colorTextOnPrimaryBackground: "#000000",
    colorBackground: "#050505",
    colorInputBackground: "#111111",
    colorInputText: "#ffffff",
    borderRadius: "0px",
  },
  elements: {
    rootBox: "font-mono",
    card: "rounded-none border border-[#222] bg-[#050505] shadow-none",
    navbar: "rounded-none border-r border-[#222]",
    scrollBox: "rounded-none",
    userButtonPopoverCard: "rounded-none border border-[#222] bg-[#050505] shadow-none",
    userButtonPopoverActionButton: "rounded-none hover:bg-primary/10 transition-colors",
    userButtonPopoverActionButtonText: "font-mono uppercase text-[10px] tracking-widest",
    userButtonPopoverActionButtonIcon: "text-primary",
    formButtonPrimary: "rounded-none bg-primary text-black hover:bg-white transition-colors font-mono uppercase tracking-widest text-xs h-10 border border-primary",
    formFieldInput: "rounded-none bg-[#111] border-[#222] focus:border-primary transition-all font-mono text-sm",
    headerTitle: "font-heading uppercase tracking-tighter text-2xl font-black",
    headerSubtitle: "font-mono uppercase text-[10px] tracking-[0.2em] text-[#888]",
    socialButtonsBlockButton: "rounded-none border-[#222] bg-[#0a0a0a] hover:bg-[#111] transition-colors font-mono uppercase text-[10px] tracking-widest",
    socialButtonsBlockButtonText: "font-mono",
    dividerLine: "bg-[#222]",
    dividerText: "font-mono uppercase text-[8px] text-[#444]",
    footerActionText: "font-mono uppercase text-[10px] text-[#666]",
    footerActionLink: "font-mono uppercase text-[10px] text-primary hover:text-white transition-colors",
    identityPreviewTextPrimary: "font-mono uppercase text-xs",
    identityPreviewEditButtonIcon: "text-primary",
    breadcrumbsItem: "font-mono uppercase text-[10px] tracking-widest",
    breadcrumbsSeparator: "text-[#333]",
    profileSectionTitleText: "font-heading uppercase tracking-widest text-sm font-bold border-b border-[#222] pb-2 w-full",
    userPreviewMainIdentifier: "font-mono uppercase text-sm tracking-tight",
    userPreviewSecondaryIdentifier: "font-mono text-[10px] text-[#666]",
    avatarBox: "rounded-none border border-primary p-1 bg-[#0a0a0a] hover:bg-[#111] transition-colors overflow-hidden",
    avatarImage: "rounded-none",
    userButtonTrigger: "rounded-none focus:outline-none focus:ring-0",
    organizationSwitcherTrigger: "rounded-none border border-[#222] bg-[#0a0a0a] font-mono uppercase text-[10px] tracking-widest hover:bg-[#111] transition-colors",
    internal: "text-primary", 
  },
  layout: {
    socialButtonsPlacement: "bottom" as const,
    shimmer: true,
  },
};
