import { dark } from "@clerk/themes";

export const clerkAppearance = {
  baseTheme: dark,
  variables: {
    colorPrimary: "#6366f1",
    colorWarning: "#ef4444",
    colorTextOnPrimaryBackground: "#ffffff",
    colorBackground: "transparent",
    colorInputBackground: "rgba(255, 255, 255, 0.08)",
    colorInputText: "#ffffff",
    colorText: "#ffffff",
    colorTextSecondary: "#a1a1aa",
    borderRadius: "1rem",
    fontFamily: "var(--font-sans)",
  },
  elements: {
    rootBox: "w-full",
    card: "glass-panel rounded-[2rem] border border-white/5 shadow-xl shadow-black/40 p-6 sm:p-8 w-full max-w-full",
    navbar: "rounded-l-[2rem] border-r border-white/5 bg-transparent",
    scrollBox: "rounded-none",
    userButtonPopoverCard: "glass-panel rounded-3xl border border-white/10 shadow-xl shadow-black/20 bg-[#030305]/90 backdrop-blur-xl",
    userButtonPopoverActionButton: "rounded-xl hover:bg-white/5 transition-colors mx-2 my-1",
    userButtonPopoverActionButtonText: "font-medium text-sm text-white",
    userButtonPopoverActionButtonIcon: "text-muted-foreground",
    userPreviewMainIdentifier: "text-base font-semibold text-white",
    userPreviewSecondaryIdentifier: "text-xs text-muted-foreground",
    formButtonPrimary: "rounded-full bg-primary text-white hover:bg-primary/90 hover:scale-[1.02] transition-all font-medium text-sm h-11 border-none shadow-lg shadow-primary/20",
    formFieldInput: "glass-card border-white/10 h-11 rounded-xl focus:ring-1 focus:ring-primary focus:border-primary text-white text-sm px-3.5 transition-all bg-white/5",
    headerTitle: "font-heading text-3xl font-semibold tracking-tight text-white mb-1",
    headerSubtitle: "text-sm text-muted-foreground",
    socialButtonsBlockButton: "glass-card border-white/10 hover:border-white/20 hover:bg-white/10 transition-all text-white h-11 rounded-xl bg-white/5",
    socialButtonsBlockButtonText: "font-medium text-sm text-white",
    dividerLine: "bg-white/10",
    dividerText: "text-muted-foreground text-xs font-medium",
    footerActionText: "text-muted-foreground text-sm",
    footerActionLink: "text-primary hover:text-primary/90 transition-colors font-medium",
    identityPreviewTextPrimary: "text-sm font-medium text-white",
    identityPreviewEditButtonIcon: "text-primary hover:text-primary/90 transition-colors",
    breadcrumbsItem: "text-sm font-medium",
    breadcrumbsSeparator: "text-white/20",
    profileSectionTitleText: "font-heading text-lg font-semibold border-b border-white/5 pb-4 w-full text-white",
    avatarBox: "rounded-full border border-white/10 hover:border-white/20 transition-colors overflow-hidden w-9 h-9",
    avatarImage: "rounded-full object-cover",
    userButtonTrigger: "rounded-full focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-black",
    organizationSwitcherTrigger: "glass-card border-white/10 rounded-xl px-3 py-2 text-sm font-medium hover:bg-white/5 transition-colors text-white",
    internal: "text-primary", 
    formFieldLabel: "text-xs font-medium text-muted-foreground mb-1.5",
  },
  layout: {
    socialButtonsPlacement: "bottom" as const,
    shimmer: true,
  },
};
